[package]
name = "rsarc"
version = "0.1.0"
edition = "2021"

[features]
# default = ["gf64_stats"]
gf64_stats = []

[dev-dependencies]
fastrand = "2.3.0"

[dependencies]
blake3 = "1.5.5"
memmap2 = "0.9.5"
